version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: costume_db
    environment:
      POSTGRES_DB: principlesproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: punchwha2548
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: costume_app
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://db:5432/principlesproject
      spring.datasource.username: postgres
      spring.datasource.password: punchwha2548
    depends_on:
      - db

volumes:
  postgres_data: